//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Belag : Pizza
{
	public Pizza Pizza
	{
		get;
		set;
	}

	public Belag(Pizza auf)
	{
        this.Pizza = auf;
	}

}

