//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public sealed class Sardellen : Belag
{
	public Sardellen(Pizza auf) : base(auf)
	{
		
	}

	public int preis()
	{
        return 2 + this.Pizza.preis();
	}

}

