//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Zusammensetzung : Belag
{
    public Zusammensetzung()
    {
        this.Belag = new List<Belag>();
    }

    private virtual List<Belag> Belag
    {
        get;
        set;
    }

	public override int preis()
	{
        return Belag.Sum((belag) => belag.preis());
	}

	public virtual void add(Belag belag)
	{
        this.Belag.Add(belag);
	}

	public virtual void remove(Belag belag)
	{
        this.Belag.Remove(belag);
	}
}

