//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AmericanPizzas : Pizzeria
{
    public virtual string teig()
    {
        return "Dicker, luftiger Teig";
    }

    public virtual int teigPreis()
    {
        return 3;
    }

    public virtual string tomatensoße()
    {
        return "Ganz normale Tomatensoße";
    }

    public virtual int tomatensoßePreis()
    {
        return 1;
    }

    public virtual string käse()
    {
		return "Dicke Schicht stark schmelzendem Käses";
    }

    public virtual int käsePreis()
    {
        return 2;
    }

    public virtual string salami()
    {
        return "Einfach etwas Salami";
    }

    public virtual int salamiPreis()
    {
        return 1;
    }

    public virtual string schinken()
    {
        return "Einfach etwas Schinken";
    }

    public virtual int schinkenPreis()
    {
        return 1;
    }

    public virtual string paprika()
    {
        return "Nur das minimal nötigste an Paprika";
    }

    public virtual int paprikaPreis()
    {
        return 1;
    }

    public virtual string sardellen()
    {
        return "Etwas Fisch";
    }

    public virtual int sardellenPreis()
    {
        return 2;
    }

}

