//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AmericanPizzas : Pizzeria
{
	public virtual void teig()
	{
		throw new System.NotImplementedException();
	}

	public virtual void teigPreis()
	{
		throw new System.NotImplementedException();
	}

	public virtual void tomatensoße()
	{
		throw new System.NotImplementedException();
	}

	public virtual void tomatensoßePreis()
	{
		throw new System.NotImplementedException();
	}

	public virtual void käse()
	{
		throw new System.NotImplementedException();
	}

	public virtual void salami()
	{
		throw new System.NotImplementedException();
	}

	public virtual void käsePreis()
	{
		throw new System.NotImplementedException();
	}

	public virtual void salamiPreis()
	{
		throw new System.NotImplementedException();
	}

	public virtual void schinken()
	{
		throw new System.NotImplementedException();
	}

	public virtual void schinkenPreis()
	{
		throw new System.NotImplementedException();
	}

	public virtual void paprika()
	{
		throw new System.NotImplementedException();
	}

	public virtual void paprikaPreis()
	{
		throw new System.NotImplementedException();
	}

	public virtual void sardellen()
	{
		throw new System.NotImplementedException();
	}

	public virtual void sardellenPreis()
	{
		throw new System.NotImplementedException();
	}

}

