//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Margherita : Pizza
{
	public override int kosten()
	{
        return this.Pizzeria.teigPreis() + this.Pizzeria.tomatensoßePreis() + this.Pizzeria.käsePreis();
	}

	public override string rezept()
	{
        return this.Pizzeria.teig() + '\n' + this.Pizzeria.tomatensoße() + '\n' + this.Pizzeria.käse() + '\n';
	}

    public Margherita(Pizzeria laden)
        : base(laden)
    {
        // TODO FIXME kann ich den Methodenrumpf irgendwie wegblenden
    }
}

