//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Napoli : Pizza
{
	public override int kosten()
	{
		throw new System.NotImplementedException();
	}

	public override string rezept()
	{
		throw new System.NotImplementedException();
	}

}

