//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Napoli : Pizza
{
	public override int kosten()
	{
        return this.Pizzeria.teigPreis() + this.Pizzeria.tomatensoßePreis() + this.Pizzeria.käsePreis() + this.Pizzeria.sardellenPreis();
	}

	public override string[] rezept()
	{
        string[] result = { this.Pizzeria.teig(), this.Pizzeria.tomatensoße(), this.Pizzeria.käse(), this.Pizzeria.sardellen() };
        return result;
	}

    public Napoli(Pizzeria laden)
        : base(laden)
    {
        // TODO FIXME kann ich den Methodenrumpf irgendwie wegblenden
    }
}

