//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface Pizzeria 
{
	string teig();

	int teigPreis();

	string tomatensoße();

	int tomatensoßePreis();

	string käse();

	string salami();

	int käsePreis();

	int salamiPreis();

	string schinken();

	int schinkenPreis();

	string paprika();

	int paprikaPreis();

	string sardellen();

	int sardellenPreis();

}

