//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface Pizzeria 
{
	void teig();

	void teigPreis();

	void tomatensoße();

	void tomatensoßePreis();

	void käse();

	void salami();

	void käsePreis();

	void salamiPreis();

	void schinken();

	void schinkenPreis();

	void paprika();

	void paprikaPreis();

	void sardellen();

	void sardellenPreis();

}

