//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Tonis : Pizzeria
{
	public virtual string teig()
	{
		throw new System.NotImplementedException();
	}

	public virtual int teigPreis()
	{
        return 1;
	}

	public virtual string tomatensoße()
	{
		throw new System.NotImplementedException();
	}

	public virtual int tomatensoßePreis()
	{
        return 2;
	}

	public virtual string käse()
	{
		throw new System.NotImplementedException();
	}

    public virtual int käsePreis()
    {
        return 1;
    }

	public virtual string salami()
	{
		throw new System.NotImplementedException();
	}

	public virtual int salamiPreis()
	{
        return 4;
	}

	public virtual string schinken()
	{
		throw new System.NotImplementedException();
	}

	public virtual int schinkenPreis()
	{
        return 4;
	}

	public virtual string paprika()
	{
		throw new System.NotImplementedException();
	}

	public virtual int paprikaPreis()
	{
        return 1;
	}

	public virtual string sardellen()
	{
		throw new System.NotImplementedException();
	}

	public virtual int sardellenPreis()
	{
        return 3;
	}

}

