//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Napoli : Pizza
{
	public override int kosten()
	{
		throw new System.NotImplementedException();
	}

	public override string rezept()
	{
		throw new System.NotImplementedException();
	}

	public virtual Bridge::Napoli constructor(Bridge::Pizzeria laden)
	{
		throw new System.NotImplementedException();
	}

	public override string accept(KochRezeptVisitor visitor)
	{
		throw new System.NotImplementedException();
	}

	public override int durchmesser()
	{
		throw new System.NotImplementedException();
	}

}

