//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Napoli : Pizza
{
    public override int kosten()
    {
        return this.Pizzeria.teigPreis() + this.Pizzeria.tomatensoßePreis() + this.Pizzeria.käsePreis() + this.Pizzeria.sardellenPreis();
    }

    public override string[] rezept()
    {
        string[] result = { this.Pizzeria.teig(), this.Pizzeria.tomatensoße(), this.Pizzeria.käse(), this.Pizzeria.sardellen() };
        return result;
    }

    public Napoli(Pizzeria laden)
        : base(laden)
    {
        // TODO FIXME kann ich den Methodenrumpf irgendwie wegblenden
    }

	public override string[] accept(KochRezeptVisitor visitor)
	{
        return visitor.visitRezept(this);
	}

	public override int durchmesser()
	{
		throw new System.NotImplementedException();
	}

}

