//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Paolo : Koch
{
	public virtual string visitRezept(Pizza pizza)
	{
        if (pizza is Margherita)
            return "du brauchen mehr KÄSE";
        else if (pizza is Napoli)
            return "FLeisch für die Veganer und FIsch für die Vegetarier";
        else if (pizza is Koch)
            return "Ceterum autem censeo Carthaginem esse delendam";
        else
            return "Kenn ich nicht";
    }

}

