//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface Pizzeria 
{
	string teig();

	int teigPreis();

	string tomatensoße();

	int tomatensoßePreis();

	string käse();

	string salami();

	int käsePreis();

	int salamiPreis();

	string schinken();

	int schinkenPreis();

	string paprika();

	int paprikaPreis();

	string sardellen();

	int sardellenPreis();

}

