//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Tonis : Pizzeria
{
	public virtual string teig()
	{
		throw new System.NotImplementedException();
	}

	public virtual int teigPreis()
	{
		throw new System.NotImplementedException();
	}

	public virtual string tomatensoße()
	{
		throw new System.NotImplementedException();
	}

	public virtual int tomatensoßePreis()
	{
		throw new System.NotImplementedException();
	}

	public virtual string käse()
	{
		throw new System.NotImplementedException();
	}

	public virtual string salami()
	{
		throw new System.NotImplementedException();
	}

	public virtual int käsePreis()
	{
		throw new System.NotImplementedException();
	}

	public virtual int salamiPreis()
	{
		throw new System.NotImplementedException();
	}

	public virtual string schinken()
	{
		throw new System.NotImplementedException();
	}

	public virtual int schinkenPreis()
	{
		throw new System.NotImplementedException();
	}

	public virtual string paprika()
	{
		throw new System.NotImplementedException();
	}

	public virtual int paprikaPreis()
	{
		throw new System.NotImplementedException();
	}

	public virtual string sardellen()
	{
		throw new System.NotImplementedException();
	}

	public virtual int sardellenPreis()
	{
		throw new System.NotImplementedException();
	}

}

