//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Tonis : Pizzeria
{
    public virtual string teig()
    {
        return "Schön dünner Teig für besonders knusprige Pizza";
    }

    public virtual int teigPreis()
    {
        return 1;
    }

    public virtual string tomatensoße()
    {
        return "Traditionelle italienische Tomatensoße mit Oregano";
    }

    public virtual int tomatensoßePreis()
    {
        return 2;
    }

    public virtual string käse()
    {
        return "Etwas Käse";
    }

    public virtual int käsePreis()
    {
        return 1;
    }

    public virtual string salami()
    {
        return "Feinste Toskanasalami";
    }

    public virtual int salamiPreis()
    {
        return 4;
    }

    public virtual string schinken()
    {
        return "Prosciutto Cotto";
    }

    public virtual int schinkenPreis()
    {
        return 4;
    }

    public virtual string paprika()
    {
        return "Etwas Paprika";
    }

    public virtual int paprikaPreis()
    {
        return 1;
    }

    public virtual string sardellen()
    {
        return "Etwas Fisch";
    }

    public virtual int sardellenPreis()
    {
        return 3;
    }

}

